### ISSUE TITLE
Shortcut doesnt work well on windows

### ISSUE THREAD

**Issue by danielcherrington** [adenekan41/scoutbar#10]
Trying to trigger this using WIN + K on windows 11 results in windows trying to open the mirrorcast app
I have not been able to find a reliable shortcut to trigger this without triggering OS level shortcuts and cant find a way of specifying a custom shortcut to bypass the issue.

Am i doing something wrong?

**Comment by danielcherrington** [comment]
@adenekan41 do you have any feedback on this issue?

**Comment by adenekan41** [comment]
Hey @danielcherrington, 

This a good one, 

I've tested this severally on different OS. and windows didn't seem to have a problem at the point of test. a possible fix would be to shift the SCA (shortcut action) from the windows button to the `control button` so we can trigger this with 

`ctrl + k`

I'll see if I can send out a fix this week. Lets move this to `#P2`

**Comment by danielcherrington** [comment]
Thanks @adenekan41 i will test out the new version this week and see if it resolves the problem =)

**Comment by danielcherrington** [comment]
can confirm CTRL + K shortcut is now working as expected
