### ISSUE TITLE
Add callback to action fn to close scoutbar

### ISSUE THREAD

**Issue by beefancohen** [adenekan41/scoutbar#11]
**Problem**
We want to close the scoutbar after performing some action programmatically.

**Proposed Solution**
Add some `close` callback in `action` fn: 

```
action: ({ close }) => {
  // do something

  close()
}
```

**Comment by adenekan41** [comment]
Hey @beefancohen, 


This is great / well-thought-out feedback; I can think of many uses for this. Currently, you can close and reopen the Scoutbar with a stale state using the `revealScoutbar` prop, but in addition to that, we'd need a way to programmatically add this to actions to make it more seamless overall.

I'd love to implement this immediately, but I won't be able to until next week. If you have any suggestions for how to proceed, your PR will be greatly appreciated.

Thanks.
