### ISSUE TITLE
shortcut behavior unexpected in firefox

### ISSUE THREAD

**Issue by abjutus** [adenekan41/scoutbar#2]
## Steps to reproduce the issue

1. press `cmd + k` in firefox and macOS

## What's the expected result?

cursor focus in scoutbar input field

## What's the actual result?

cursor focus in firefox search box (built-in shortcut)

## Additional details / screenshot
![圖issue](https://user-images.githubusercontent.com/12343599/141687064-bfe4596d-a065-4c03-b467-8485649941b5.png)

**Comment by adenekan41** [comment]
Hey @alanaudi 

Good catch. Thanks for pointing this out. Great issues structure as well. I have reproduced this issue, and I think it has to do with me not intentionally disabling the browser defaults for the `scoutKey` method. I guess the `CMD+K` is an exception where we can just prevent the defaults for browsers.

The next patch should include a fix for this.

Great work man 🚀

**Comment by adenekan41** [comment]
hey @alanaudi , update your scoutbar to v1.1.8 for a cleaner version

**Comment by abjutus** [comment]
@adenekan41  thank you for dealing with this issue so fast !
This is a great package for building command bar, nice work 👍
