### ISSUE TITLE
 Input field behavior is wierd when typing character `k`

### ISSUE THREAD

**Issue by abjutus** [adenekan41/scoutbar#7]
## Steps to reproduce the issue

1. press `cmd + k` (chrome, firefox, safari on macOS)
2. key in character `k` anywhere, oops

## What's the expected result?
key in character `k` immediately

## What's the actual result?
`k` appears only when the key is pressed and held

## Additional details / screenshot
- scoutbar @ 1.1.8
- [demo site](https://www.alanaudi.com/demo/keyboard)

![bug-report-scoutbar-k-key](https://user-images.githubusercontent.com/12343599/146044347-f3ccafae-9f4a-439d-a9ab-922e0e777a20.gif)

**Comment by adenekan41** [comment]
That's really weird let me look into it.

**Comment by adenekan41** [comment]
Hey @alanaudi thanks for raising this a fix has been sent on a new version here 

https://www.npmjs.com/package/scoutbar/v/1.1.9
