### ISSUE TITLE
Input should have autocomplete="off"

### ISSUE THREAD

**Issue by julesbravo** [adenekan41/scoutbar#9]
If you don't have `autocomplete="off"` on the search input the browser native autocomplete may show.

![image](https://user-images.githubusercontent.com/194692/181832163-0a8a5084-6303-478a-a50a-bc4f28121271.png)

**Comment by adenekan41** [comment]
Hey @julesbravo, 

Thanks for the feedback, this has been added to this build 
https://www.npmjs.com/package/scoutbar/v/1.1.11

#### Follow up
Update `scoutbar` Documentation
